import React, { useEffect } from 'react'
import Logout from '../Logout'
import { useNavigate } from 'react-router-dom'

function About(props) {
  const { currentUser } = props
  let navigate = useNavigate()

  if (!currentUser) {
    return navigate("/")
  }

  return (
    <>
      <h1>Picture Book FAQ</h1>
      <h2>What is AI?</h2>
      <h3>Artificial Intelligence (AI) is the simulation of human intelligence in machines that are programmed to think and learn like humans. It encompasses a wide range of technologies and techniques, such as machine learning, natural language processing, and robotics, that enable computers to perceive, reason, and act autonomously.</h3>

      <h2>What runs this app?</h2>
      <h3>This particular AI technology, powered by GPT-3, helps us generate delightful short stories for children. These stories are not only engaging and entertaining but also written in a way that's easy for kids to understand. The AI algorithm behind the scenes ensures that each story is unique, and tailored to the interests of young readers. Giving them the opportunity to explore new worlds, characters and imagination. Making reading fun and exciting for them.</h3>



      <h2>Is using AI to write stories ethical?</h2>
      <h3>There is some concern that AI could be used to create art, music, and writing that could replace human creators, potentially leading to job loss and other negative consequences. However, it's worth noting that AI is simply a tool that can be used to augment the creative process, rather than replace it. Some artists, musicians and writers find AI as an inspiration and helpful tool to generate new idea or explore possibilities, but ultimately the final creative decision is always in the hands of the artist. Additionally, as AI technology continues to advance, it is also possible for it to create new opportunities and markets for human creators, such as allowing them to more easily create and distribute their work to a wider audience.</h3>
      <h3>
        Another important perspective is that AI can help democratize the creative process, providing a tool that can generate new and unique content to people with less resources or opportunities.
        Overall, it's important to consider the potential impact of AI on creative industries and take steps to ensure that the benefits of the technology are shared fairly.
      </h3>

      <h2>Can I sell or republish these stories?</h2>
      <h3>
        Whether you can sell something that was written by GPT-3 depends on the specific use case and the licensing terms of the specific GPT-3 model you are using. See HERE.
      </h3>
      <h3>
        GPT-3 is a proprietary machine learning model developed and owned by OpenAI, and the company has implemented specific terms of service and license agreements that dictate how the model can be used and by whom. In general, they do not allow commercial use without a commercial license, also the specific terms of service and license agreements vary depending on which GPT-3 service you are using.
      </h3>
      <h3>
        Please look at the license agreement and also consult with a legal professional before attempting to sell something that was generated by GPT-3.
      </h3>


      <h2>Can I sell the stories or artwork made from picture book?</h2>
      <h3>
        Whether you can sell something that was written by GPT-3 depends on the specific use case and the licensing terms of the specific GPT-3 model you are using.
      </h3>
      <h3>
        GPT-3 is a proprietary machine learning model developed and owned by OpenAI, and the company has implemented specific terms of service and license agreements that dictate how the model can be used and by whom. In general, they do not allow commercial use without a commercial license, also the specific terms of service and license agreements vary depending on which GPT-3 service you are using.
      </h3>
      <h3>
        Please look at the license agreement and also consult with a legal professional before attempting to sell something that was generated by GPT-3.
      </h3>

      <h2>What can I do with these stories</h2>
      <h3>blablabla</h3>


    </>
  )
}

export default About
